models:
  - name: stg_matches
    columns:
      - name: match_id
        tests:
          - not_null
          - unique
      - name: home_team_id
        tests:
          - not_null
      - name: away_team_id
        tests:
          - not_null
      - name: fulltime_home_goals
        tests:
          - not_null
      - name: fulltime_away_goals
        tests:
          - not_null
      - name: utc_date
        tests:
          - not_null
      - name: matchday
        tests:
          - not_null
      - name: season_id
        tests:
          - not_null
      - name: winner
        tests:
          - accepted_values: 
              arguments:
                values: [HOME_TEAM, AWAY_TEAM, DRAW]
  - name: stg_scorers
    columns:
      - name: player_season_id
        tests:
          - not_null
          - unique
      - name: player_id
        tests:
          - not_null
      - name: season_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: played_matches
        tests:
          - not_null
      - name: goals
        tests:
          - not_null
      - name: assists
        tests:
          - not_null
      - name: penalties
        tests:
          - not_null
  - name: int_team_performance
    columns:
      - name: match_team_id
        tests:
          - not_null
          - unique
      - name: team_id
        tests:
          - not_null
      - name: match_id
        tests:
          - not_null
      - name: fulltime_goals_scored
        tests:
          - not_null
      - name: fulltime_goals_conceded
        tests:
          - not_null
      - name: utc_date
        tests:
          - not_null
      - name: matchday
        tests:
          - not_null
      - name: season_id
        tests:
          - not_null
      - name: result
        tests:
          - accepted_values: 
              arguments:
                values: [WIN, LOSE, DRAW]
  - name: dim_teams
    columns:
      - name: team_id
        tests:
          - not_null
          - unique
  - name: dim_players
    columns:
      - name: player_id
        tests:
          - not_null
          - unique